config/routes.rb
Rails.application.routes.draw do
  resources :shorten_urls do
    get 'shorten_urls' => 'shorten_urls#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shorten_url.rb
class ShortenUrl < ApplicationRecord
  validates_presence_of :original_url

  def generate_short_url
    self.short_url = "http://" + SecureRandom.uuid[0..5] if self.short_url.nil?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shorten_urls_controller.rb
class ShortenUrlsController < ApplicationController
  before_action :set_shorten_url, only: [:show, :edit, :update, :destroy]

  # GET /shorten_urls
  # GET /shorten_urls.json
  def index
    @shorten_urls = ShortenUrl.all
  end

  # GET /shorten_urls/1
  # GET /shorten_urls/1.json
  def show
    @shorten_url = ShortenUrl.find(params[:id])
  end

  # GET /shorten_urls/new
  def new
    @shorten_url = ShortenUrl.new
  end

  # GET /shorten_urls/1/edit
  def edit
  end

  # POST /shorten_urls
  # POST /shorten_urls.json
  def create
    @shorten_url = ShortenUrl.find_or_create_by(shorten_url_params)
    if @shorten_url.short_url != nil
      @shorten_url.short_url
    else
      @shorten_url.short_url = @shorten_url.generate_short_url()
    end

      respond_to do |format|
        if @shorten_url.save
          format.html { redirect_to @shorten_url, notice: 'Shorten url was successfully created.' }
          format.json { render :show, status: :created, location: @shorten_url }
        else
          format.html { render :new }
          format.json { render json: @shorten_url.errors, status: :unprocessable_entity }
        end
      end
  end

  def update
    respond_to do |format|
      if @shorten_url.update(shorten_url_params)
        format.html { redirect_to @shorten_url, notice: 'Shorten url was successfully updated.' }
        format.json { render :show, status: :ok, location: @shorten_url }
      else
        format.html { render :edit }
        format.json { render json: @shorten_url.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @shorten_url.destroy
    respond_to do |format|
      format.html { redirect_to shorten_urls_url, notice: 'Shorten url was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shorten_url
      @shorten_url = ShortenUrl.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def shorten_url_params
      params.require(:shorten_url).permit(:original_url, :short_url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redis = Redis.new(host: "redis", port: 6379)
    redis.incr "page hits"

    @page_hits = redis.get "page hits"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorten_urls_helper.rb
module ShortenUrlsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Littleurl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shorten_urls/_form.html.erb
<%= form_for(shorten_url) do |f| %>
  <% if shorten_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shorten_url.errors.count, "error") %> prohibited this shorten_url from being saved:</h2>

      <ul>
      <% shorten_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :original_url %>
    <%= f.text_area :original_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shorten_urls/edit.html.erb
<h1>Editing Shorten Url</h1>

<%= render 'form', shorten_url: @shorten_url %>

<%= link_to 'Show', @shorten_url %> |
<%= link_to 'Back', shorten_urls_path %>

app/views/shorten_urls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shorten Urls</h1>
<table>
  <tr>
    <th>Original Url</th>
    <th>Short Url</th>
  </tr>

<% @shorten_urls.each do |shorten_url| %>
  <tr>
    <td><%= shorten_url.original_url %></td>
    <td><%= shorten_url.short_url %></td>
    <td><%= link_to 'Show', shorten_url %></td>
    <td><%= link_to 'Edit', edit_shorten_url_path(shorten_url) %></td>
    <td><%= link_to 'Destroy', shorten_url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'New Shorten Url', new_shorten_url_path %>

app/views/shorten_urls/new.html.erb
<h1>New Shorten Url</h1>

<%= render 'form', shorten_url: @shorten_url %>

<%= link_to 'Back', shorten_urls_path %>

app/views/shorten_urls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Original url:</strong>
  <%= @shorten_url.original_url %>
</p>

<p>
  <strong>Short url:</strong>
  <%= @shorten_url.short_url %>
</p>

<%= link_to 'Back', shorten_urls_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<h1>This page has been viewed <%= pluralize(@page_hits, 'time') %>!</h1>